version: 2
updates:
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-intl
    versions:
    - 5.11.0
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.4
    - 5.12.5
    - 5.13.0
    - 5.13.1
    - 5.13.2
    - 5.13.3
    - 5.13.4
    - 5.13.5
    - 5.14.0
    - 5.14.1
    - 5.15.0
    - 5.15.1
    - 5.15.3
    - 5.15.5
    - 5.15.6
    - 5.15.7
    - 5.15.8
    - 5.16.0
    - 5.17.0
    - 5.17.1
  - dependency-name: "@formatjs/intl-pluralrules"
    versions:
    - 4.0.10
    - 4.0.11
    - 4.0.12
    - 4.0.13
    - 4.0.14
    - 4.0.15
    - 4.0.6
    - 4.0.7
    - 4.0.8
    - 4.0.9
  - dependency-name: "@formatjs/intl-locale"
    versions:
    - 2.4.14
    - 2.4.15
    - 2.4.16
    - 2.4.17
    - 2.4.18
    - 2.4.19
    - 2.4.20
    - 2.4.21
    - 2.4.22
  - dependency-name: "@formatjs/intl-relativetimeformat"
    versions:
    - 8.0.4
    - 8.0.5
    - 8.0.6
    - 8.1.0
    - 8.1.1
    - 8.1.2
    - 8.1.3
    - 8.1.4
    - 8.1.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: msw
    versions:
    - 0.26.0
    - 0.26.1
    - 0.26.2
    - 0.27.0
    - 0.27.1
    - 0.27.2
    - 0.28.0
    - 0.28.1
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python-dotenv
    versions:
    - 0.15.0
    - 0.16.0
    - 0.17.0
  - dependency-name: sentry-sdk[flask]
    versions:
    - 0.19.5
    - 0.20.3
  - dependency-name: urllib3
    versions:
    - 1.26.3
  - dependency-name: cachetools
    versions:
    - 4.2.1
  - dependency-name: pytz
    versions:
    - "2020.5"
  - dependency-name: unidecode
    versions:
    - 1.1.2
